<!--
Generated by: x_legatus_scriba_machina_x.factory
Source: C:/x_runner_x/x_legatus_scriba_machina_x/factory/templates/make_markdown/out_docs/alice_in_wonderland.md.tmpl
Commit: 85eeebefe6edf1ebdac6e916e1a614ac7444ea76
Rendered: 2025-11-21T22:12:20+00:00
-->
- [1 Alice's Adventures in Wonderland](#1-alice's-adventures-in-wonderland)
  - [1.1 Down the Rabbit-Hole](#11-down-the-rabbit-hole)
  - [1.2 A Curious Bottle](#12-a-curious-bottle)
  - [1.3 Conclusion](#13-conclusion)

# 1 Alice's Adventures in Wonderland
Public-domain sampler inspired by Lewis Carroll (1865).

## 1.1 Down the Rabbit-Hole
Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it...

1. Sees a White Rabbit with a pocket watch2. Follows it down the rabbit-hole3. Finds a hall with many locked doors
## 1.2 A Curious Bottle
On a little table she found a bottle, on it was a paper label, with the words "DRINK ME" beautifully printed on it.

Item | Effect
--- | ---
Cake (EAT ME) | Grows tall
Fan | Shrinks
Key | Opens small door

![Alice meets the White Rabbit (Tenniel, public domain)](https://upload.wikimedia.org/wikipedia/commons/6/6f/Alice_par_John_Tenniel_02.png)

## 1.3 Conclusion
This document demonstrates headers with numbering and TOC, lists, tables, and images.
